# Generated by Django 2.2 on 2021-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20210409_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='list_of_additional_subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='list_of_additional_subjects',
            field=models.ManyToManyField(blank=True, null=True, to='exchange.Subject'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='list_of_classes',
        ),
        migrations.AddField(
            model_name='student',
            name='list_of_classes',
            field=models.ManyToManyField(blank=True, null=True, to='exchange.Class'),
        ),
    ]
