# Generated by Django 2.2 on 2021-04-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210410_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='list_of_classes',
        ),
    ]
