# Generated by Django 3.2 on 2021-04-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='exchange',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange'),
        ),
    ]
