# Generated by Django 3.2 on 2021-04-12 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0007_auto_20210412_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(null=True)),
                ('modification_date', models.DateField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('semester', models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8'), (9, 'Sem9'), (10, 'Sem10')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.subject'),
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='week',
            field=models.CharField(choices=[('A', 'Week A'), ('B', 'Week B')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='additional_information',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.class'),
        ),
        migrations.AddField(
            model_name='offer',
            name='other_student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Reserved'), ('T', 'Taken')], default=('A', 'Active'), max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='path',
            field=models.CharField(choices=[('A', 'Algorythmic path'), ('AA', 'Algorythmic-application path'), ('SD', 'Software development path')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='mandatory',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='path',
            field=models.CharField(choices=[('A', 'Algorythmic path'), ('AA', 'Algorythmic-application path'), ('SD', 'Software development path')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Sem1'), (2, 'Sem2'), (3, 'Sem3'), (4, 'Sem4'), (5, 'Sem5'), (6, 'Sem6'), (7, 'Sem7'), (8, 'Sem8'), (9, 'Sem9'), (10, 'Sem10')], null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('inż.', 'inżynier'), ('mgr. inż.', 'magister inżynier'), ('dr.', 'doktor'), ('dr. inż.', 'doktor inżynier')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='room',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.teacher'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='other_offer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='list_of_additional_subjects',
            field=models.ManyToManyField(to='exchange.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='list_of_classes',
            field=models.ManyToManyField(to='exchange.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.exchange'),
        ),
    ]
