# Generated by Django 3.1.2 on 2021-04-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20210413_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('C', 'Closed')], default=('N', 'New'), max_length=10),
        ),
    ]
