# Generated by Django 3.1.2 on 2021-04-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20210413_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='other_offer_id',
            new_name='other_offer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='other_student_id',
            new_name='other_student',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='class_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='preferred_classes',
            field=models.ManyToManyField(related_name='user_preferences', to='exchange.Class'),
        ),
        migrations.AddField(
            model_name='offer',
            name='preferred_teachers',
            field=models.ManyToManyField(to='exchange.Teacher'),
        ),
        migrations.AddField(
            model_name='offer',
            name='unwanted_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unwanted_class', to='exchange.class'),
        ),
    ]
