# Generated by Django 3.1.2 on 2021-05-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0012_remove_offer_preferred_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='modification_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='exchange',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='modification_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='acceptable_classes',
            field=models.ManyToManyField(related_name='user_yellow', to='exchange.Class'),
        ),
        migrations.AddField(
            model_name='offer',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='preferred_classes',
            field=models.ManyToManyField(related_name='user_green', to='exchange.Class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(choices=[('Pn', 'Poniedziałek'), ('Wt', 'Wtorek'), ('Śr', 'Środa'), ('Czw', 'Czwartek'), ('Pt', 'Piątek')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='other_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.offer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
