# Generated by Django 3.2.4 on 2021-06-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_auto_20210510_1911'),
        ('exchange', '0016_auto_20210509_1531'),
    ]

    operations = [
    ]
