# Generated by Django 3.2.4 on 2021-06-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_merge_0014_auto_20210510_1911_0016_auto_20210509_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subscribed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='modification_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='acceptable_classes',
            field=models.ManyToManyField(null=True, related_name='user_yellow', to='exchange.Class'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='preferred_classes',
            field=models.ManyToManyField(null=True, related_name='user_green', to='exchange.Class'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='preferred_teachers',
            field=models.ManyToManyField(null=True, to='exchange.Teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='list_of_additional_subjects',
            field=models.ManyToManyField(blank=True, to='exchange.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='list_of_classes',
            field=models.ManyToManyField(blank=True, to='exchange.Class'),
        ),
    ]
