# Generated by Django 3.2.4 on 2021-06-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_auto_20210609_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('C', 'Closed'), ('A', 'Archived')], default=('N', 'New'), max_length=10),
        ),
    ]
