# Generated by Django 2.2 on 2021-04-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_student_list_of_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='list_of_classes',
            field=models.ManyToManyField(blank=True, null=True, to='exchange.Class'),
        ),
    ]
